### ISSUE TITLE
`TestServerPublishSpecific` is flaky

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#212]
```
--- FAIL: TestServerPublishSpecific (2.02s)
    server_test.go:274: 
        	Error Trace:	/home/runner/work/hypersdk/hypersdk/pubsub/server_test.go:274
        	Error:      	connection was not closed on the server side
        	Test:       	TestServerPublishSpecific
FAIL
```

**Comment by patrick-ogrady** [comment]
Also saw this fail: 

```text
github.com/ava-labs/hypersdk/pubsub	coverage: 38.5% of statements
panic: test timed out after 3m0s
running tests:
	TestServerPublish (3m0s)

goroutine 14 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2241 +0x[21](https://github.com/ava-labs/hypersdk/actions/runs/5589049183/jobs/10216749585#step:4:22)9
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.6/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001304e0, {0x908261, 0x11}, 0x938170)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc0001304e0, 0xc000157b40)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc000111360?, {0xbb57a0, 0x3, 0x3}, {0x1c?, 0x4a7279?, 0xbbda20?})
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc000111360)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:82 +0x2fd

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f17917937b8, 0x72)
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00009e198, 0xc0000b0000?, 0x0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00009e180, {0xc0000b0000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_unix.go:167 +0x405
net.(*netFD).Read(0xc00009e180, {0xc0000b0000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc0000a2020, {0xc0000b0000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/net.go:183 +0xb1
bufio.(*Reader).fill(0xc0000a61e0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/bufio/bufio.go:106 +0x2ab
bufio.(*Reader).Peek(0xc0000a61e0, 0x2)
	/opt/hostedtoolcache/go/1.20.6/x64/src/bufio/bufio.go:144 +0xd2
github.com/gorilla/websocket.(*Conn).read(0xc0000b8000, 0x0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:371 +0x5d
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0000b8000)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:809 +0x12c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000b8000)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1009 +0x16b
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00007f5c0?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x31
github.com/ava-labs/hypersdk/pubsub.TestServerPublish(0xc000130680)
	/home/runner/work/hypersdk/hypersdk/pubsub/server_test.go:84 +0x965
testing.tRunner(0xc000130680, 0x938170)
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.6/x64/src/testing/testing.go:1629 +0x806

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f17917938a8, 0x72)
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000146518, 0x46d501?, 0x0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000146500)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_unix.go:614 +0x425
net.(*netFD).accept(0xc000146500)
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/fd_unix.go:172 +0x4a
net.(*TCPListener).accept(0xc00001[22](https://github.com/ava-labs/hypersdk/actions/runs/5589049183/jobs/10216749585#step:4:23)88)
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/tcpsock_posix.go:148 +0x45
net.(*TCPListener).Accept(0xc000012288)
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/tcpsock.go:297 +0x68
net/http.(*Server).Serve(0xc00016a000, {0x9a57d0, 0xc000012288})
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/http/server.go:3059 +0x5a7
net/http.(*Server).ListenAndServe(0xc00016a000)
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/http/server.go:2988 +0xc5
github.com/ava-labs/hypersdk/pubsub.TestServerPublish.func1()
	/home/runner/work/hypersdk/hypersdk/pubsub/server_test.go:69 +0x[23](https://github.com/ava-labs/hypersdk/actions/runs/5589049183/jobs/10216749585#step:4:24)5
created by github.com/ava-labs/hypersdk/pubsub.TestServerPublish
	/home/runner/work/hypersdk/hypersdk/pubsub/server_test.go:61 +0x766

goroutine 12 [select]:
github.com/ava-labs/hypersdk/pubsub.(*Connection).writePump(0xc0000605e0)
	/home/runner/work/hypersdk/hypersdk/pubsub/connection.go:125 +0x269
created by github.com/ava-labs/hypersdk/pubsub.(*Server).addConnection
	/home/runner/work/hypersdk/hypersdk/pubsub/server.go:123 +0x125

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7f17917936c8, 0x72)
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000146618, 0xc0000d8000?, 0x0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000146600, {0xc0000d8000, 0x400, 0x400})
	/opt/hostedtoolcache/go/1.20.6/x64/src/internal/poll/fd_unix.go:167 +0x405
net.(*netFD).Read(0xc000146600, {0xc0000d8000, 0x400, 0x400})
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000014108, {0xc0000d8000, 0x400, 0x400})
	/opt/hostedtoolcache/go/1.20.6/x64/src/net/net.go:183 +0xb1
bufio.(*Reader).fill(0xc0000a62a0)
	/opt/hostedtoolcache/go/1.20.6/x64/src/bufio/bufio.go:106 +0x2ab
bufio.(*Reader).Peek(0xc0000a62a0, 0x2)
	/opt/hostedtoolcache/go/1.20.6/x64/src/bufio/bufio.go:144 +0xd2
github.com/gorilla/websocket.(*Conn).read(0xc0000b82c0, 0xc000052a98?)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:371 +0x5d
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0000b82c0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:809 +0x12c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000b82c0)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1009 +0x16b
github.com/ava-labs/hypersdk/pubsub.(*Connection).readPump(0xc0000605e0)
	/home/runner/work/hypersdk/hypersdk/pubsub/connection.go:82 +0x445
created by github.com/ava-labs/hypersdk/pubsub.(*Server).addConnection
	/home/runner/work/hypersdk/hypersdk/pubsub/server.go:1[24](https://github.com/ava-labs/hypersdk/actions/runs/5589049183/jobs/10216749585#step:4:25) +0x18f
```

**Comment by patrick-ogrady** [comment]
Still flaky: https://github.com/ava-labs/hypersdk/actions/runs/5674266757/job/15377536161?pr=297
